name: Build impedance.py
description: |
  Composite workflow to re-use the build of impedance.py using poetry.

inputs:
  poetry-version:
    description: "The version of poetry to install."
    default: "1.5.1"
    type: string
    required: false
  python-version:
    description: "The version of Python to use for setup-python."
    default: "3.10"
    type: string
    required: false
  poetry-install-group:
    description: "To install a specific poetry group."
    default: ""
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        if [ "${{ inputs.poetry-version }}" != "" ]; then
          pipx install poetry==${{ inputs.poetry-version }}
        else
          pipx install poetry
        fi

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install impedance.py
      shell: bash
      run: |
        poetry env use ${{ inputs.python-version }}
        if [ "${{ poetry-install-group }}" != "" ]; then
          poetry install --with ${{ poetry-install-group }};
        else
          poetry install;
        fi
